languageCode: "en-gb"
title: "Geoffrey's Website"

pygmentsUseClasses: true

minify:
  disableSVG: true

outputs:
  home:
    - HTML
  posts:
    - HTML
    - RSS

menu:
  main:
    - identifier: homepage
      name: Home
      url: /
      weight: -110
    - name: Posts
      url: /posts/
      weight: -100