languageCode: "en-gb"
title: "Geoffrey's Website"

pygmentsUseClasses: true

minify:
  disableSVG: true

outputs:
  home:
    - HTML
  posts:
    - HTML
    - RSS

pluralizeListTitles: false

menu:
  main:
    - name: Home
      url: /
      weight: -120
    - name: About
      url: /about/
      weight: -110
    - name: Computing
      url: /categories/computing/
      weight: -100
    - name: Running
      url: /categories/running/
      weight: -90