languageCode: "en-gb"
title: "Geoffrey's Blog"

pygmentsUseClasses: true

minify:
  disableSVG: true

outputs:
  home:
    - HTML
  post:
    - HTML
    - RSS
    -

menu:
  main:
    - identifier: homepage
      name: Home
      url: /
      weight: -110
    - name: Blog
      url: /blog/
      weight: -100